### ISSUE TITLE
能不能提供一份安装说明呢？Could you provide an installation guide?

### ISSUE THREAD

**Issue by Ranglage** [gaoyi/SlicerVirtualEndoscopy#1]
是要跟slicer联合编译嘛？还是单独编译，然后怎么导入到slicer中？
谢谢高老师

Prof Gao
Do these modules have to compile together with slicer? Or compile alone and how to import to slicer?
Thank you

**Comment by CCxxCxCxCx** [comment]
@Ranglage  您好， 请问您编译成功了吗？

**Comment by Ranglage** [comment]
> @Ranglage 您好， 请问您编译成功了吗？
嗯嗯，不过后来我司自己用OpenGL写的虚拟内镜了。加了一些图形学的功能，把管壁后方的一些结构也展示出来了。可惜赶上医疗反腐，不一定能活得下去。
